#!/bin/bash
#
# This script calculates the energy bandgap (if any) of a system.
# Also, optionally, it shifts the energy levels regarding the Fermi level (if a metal), or the valence band maximum (if an insulating system).
####
####
# It is important to keep the following files in the same directory while running this script:
# pwscf output, the output generated bands.x, and the two-column file generated by plotbands.x
####
####
# This script should be run as ./script <pwscf-output> <output-bands.x> <output-plotband.x> <shifted-bands>(optionally)

echo -e "This program will provide you a file with band structure energy levels shifted, as well as, the band gap value (if any).\nIf not, it will inform you whether the system is metallic ot not."
echo -e "==========================================================================================\n==========================================================================================\n"
fermi=$(grep Fermi $1 | awk '{print $5}')
echo -e "The calculated Fermi level is: $fermi eV.\n"
echo -e "==========================================================================================\n==========================================================================================\n"
num_elec=$(grep "number of electrons" $1 | cut -d '.' -f 1 | cut -d '=' -f 2)
echo -e "The # of valence electrons in the unit cell is $num_elec."
echo -e "==========================================================================================\n"
num_ks=$(grep "^$" $3 | wc -l)
echo -e "The # of Kohn-Sham states is $num_ks."
echo -e "==========================================================================================\n"
num_kpts=$(echo "$(grep -v "^$" $3 | wc -l) / $num_ks" | bc)
############
############
# Checking the number of band levels.
############
############
if [ $(($num_elec%2)) -eq 0 ]
then
	num_val_bands=$(echo "$num_elec/2" | bc)
	echo -e "The number of valence bands is $num_val_bands."
	num_cond_bands=$(echo "$num_ks-$num_val_bands" | bc)
	echo -e "The number of conduction bands is $num_cond_bands."
else
	num_val_bands=$(echo "$num_elec/2+1" | bc)
        echo -e "The number of valence bands is $num_val_bands."
        num_cond_bands=$(echo "$num_ks-$num_val_bands" | bc)
        echo -e "The number of conduction bands is $num_cond_bands."
fi
echo -e "==========================================================================================\n"
############
############
# Defining what are the high-symmetry k-points acconding to the ones showed by the bands.x output.
############
############
echo -e "The high-symmetry points you have informed in the pw bands calculations are:\n$(grep "high-symmetry" $2)"
echo -e "==========================================================================================\n"
############
############
# Getting the VBM and CBM, as well as its k-points positions.
############
############
vbm=$(cat $3 | head -$(($(($num_kpts+1))*$num_val_bands)) | tail -$(($num_kpts+1)) | awk '{print $2}' | sort -n | tail -1)
echo -e "The VBM is $vbm eV."
#echo -e "There are(is) $(grep $vmb | wc -l) k-points with the same VBM."
#kpts_vbm=$(cat $3 | head -$(($(($num_kpts+1))*$num_val_bands)) | tail -$(($num_kpts+1)))
#echo -e "There are(is) $(grep $vbm $kpts_vbm | wc -l) k-points with the same VBM, namely\n$(grep $vbm $kpts_vbm)"
cat $3 | head -$(($(($num_kpts+1))*$num_val_bands)) | tail -$(($num_kpts+1)) | echo -e "There are(is) $(grep -E "[+-]?$vbm" | wc -l) k-points with the same VBM, namely\n$(cat $3 | head -$(($(($num_kpts+1))*$num_val_bands)) | tail -$(($num_kpts+1)) | grep -E "[+-]?$vbm")"
echo -e "Please, check if one of these points is a high-symmetric one.\n"
cbm=$(cat $3 | head -$(($(($num_kpts+1))*$(($num_val_bands+1)))) | tail -$(($num_kpts+1)) | head -$num_kpts |  awk '{print $2}' | sort -r | tail -1)
echo -e "The CBM is $cbm eV."
cat $3 | head -$(($(($num_kpts+1))*$(($num_val_bands+1)))) | tail -$(($num_kpts+1)) | echo -e "There are(is) $(grep -E "[+-]?$cbm" | wc -l) k-points with the same CBM, namely\n$(cat $3 | head -$(($(($num_kpts+1))*$(($num_val_bands+1)))) | tail -$(($num_kpts+1)) | grep -E "[+-]?$cbm")"
echo -e "Also, check if one of these points is a high-symmetric one."
echo -e "==========================================================================================\n"
#####################
##################### Checking if the system is metallic.   
#####################
gap=$(echo "scale=4;$cbm-$vbm" | bc)
echo -e "Checking whether the system is metallic or not...\n"
if (( $(bc <<<"$vbm >= $fermi || $gap < 0.0001") ))
then
	echo -e "The system is metallic. Its Fermi energy is $fermi eV."
	echo -e "==========================================================================================\n"
else
	echo -e "The system is not metallic.\nIts energy bandgap is $gap eV."
	vbm_kpt=$(cat $3 | head -$(($(($num_kpts+1))*$num_val_bands)) | tail -$(($num_kpts+1)) | grep -E "[+-]?$vbm" | sort -r | tail -1 | awk '{print $1}')
	cbm_kpt=$(cat $3 | head -$(($(($num_kpts+1))*$(($num_val_bands+1)))) | tail -$(($num_kpts+1)) | grep -E "[+-]?$cbm" | sort -r | tail -1 | awk '{print $1}')
	if (( $(bc <<<"$vbm_kpt = $cbm_kpt") ))
	then
		echo -e "The gap is a direct gap at $vbm_kpt."
		echo -e "==========================================================================================\n"
	else
		echo -e "The gap is a indirect gap, where\nthe VBM is located at $vbm_kpt,\nand the CBM is located at $cbm_kpt."
		echo -e "==========================================================================================\n"
	fi
fi
###################
################### Building the file with the energy column shifted by the Fermi energy.
###################
read -p "Do you want a two-column file (as the one you have used)? 'y' or any another letter? " quest
if [ $quest == y ]
then
	read -p "Is the system metallic? 'y' or any other letter. " quest2
	if [ $quest2 == y ]
	then
		echo -e "\nThe system is metallic...\nGenerating the two-column file."
		sleep 5
		awk '{print $1}' $3 > col1
		fermi_chg=$(echo -E "-1 * $fermi" | bc | awk '{printf "%8.4f", $0}')
		awk -v factor=$fermi '{printf "%8.4f\n", ($2-factor)}' $3 | sed -E "s/[+-]?$fermi_chg/   /g" > col2
		paste col1 col2 > $4
		rm col1 col2
		echo -e "\nThe new two-columns band structure file has been created. Its second column has been shifted by the Fermi level."
		echo -e "==========================================================================================\n"
	else
		echo -e "\nThe system is not metallic...\nGenerating the two-column file."
		sleep 5
		awk '{print $1}' $3 > col1
		fermi_chg=$(echo -E "-1 * $vbm" | bc | awk '{printf "%8.4f", $0}')
		awk -v factor=$vbm '{printf "%8.4f\n", ($2-factor)}' $3 | sed -E "s/[+-]?$fermi_chg/   /g" > col2
		paste col1 col2 > $4
		rm col1 col2
		echo -e "\nThe new two-columns band structure file has been created. Its second column has been shifted by the VBM energy."
		echo -e "==========================================================================================\n"
	fi
else
	echo -e "Ok. You don't want this file. Moving on!."
	echo -e "==========================================================================================\n"
fi

echo -e "Done!"
